name: quickdeal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.14

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.1
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  fpdart: ^1.1.1
  supabase_flutter: ^2.8.4
  dartz: ^0.10.1
  image_picker: ^1.1.2
  file_picker: ^9.2.3
  circle_nav_bar: ^2.2.0
  mime: ^2.0.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  flutter_pdfview: ^1.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - env/